### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by mfiano** [lispgames/cl-sdl2-image#1]
Been grepping the API for a while and I cannot figure out how to get the array of pixels, width, and height from the resulting SDL2 surface. Could you provide an example on how to use this to pass an image to an OpenGL texture?

**Comment by rpav** [comment]
There is no API per se; these are struct members of [SDL_Surface](https://wiki.libsdl.org/SDL_Surface), so an example might be:

``` lisp
(plus-c:c-let ((surface sdl2-ffi:sdl-surface :from (sdl2-image:load-image ...)))
  (format t "Image is ~Ax~A~%" (surface :w) (surface :h)))
```

..which I didn't actually run to test, but you get the idea.

**Comment by rpav** [comment]
(Obviously I didn't test since that should be `(surface :w)` and `(surface :h)`).

**Comment by mfiano** [comment]
Where does this C-LET stuff come from? How do I get the data? I was doing this with lispbuilder-sdl:

```
(sdl-base::with-pixel (pixels (sdl:fp surface))
        (sdl-base::pixel-data pixels)))
```

**Comment by rpav** [comment]
`c-let` is from [`cl-plus-c`](https://github.com/rpav/cl-autowrap/blob/master/cl-plus-c.md) which is part of autowrap, and probably the easiest way to get at this data.  I've updated the above to reflect this and (hopefully) be "correct".

**Comment by mfiano** [comment]
Ok, I can get the width and height perfectly like this. But I'm not sure how to get the pixel format or the array of pixel data. It appears that this is (surface :format) and (surface :pixels) respectively, but I get #.(SB-SYS:INT-SAP #X7FFFC631E5E0) returned. What am I doing wrong?

I need to detect the 2 possible formats I use, RGB or RGBA, and obtain the actual pixel data as a lisp array.
