### ISSUE TITLE
Unable to load libSDL2

### ISSUE THREAD

**Issue by BHO1** [lispgames/cl-sdl2-image#6]
using debian 9.0,  SBCL 1.3.1
and evaluating
CL-USER> (ql:quickload :sdl2-image)
got me the error 

Unable to load any of the alternatives:
   ("libSDL2_image-2.0.so.0" "libSDL2_image")

After the first time i installed libSDL2 and choose the [retry] option in debugger. This did not work, nor did any effort like restarting lisp, (ql:uninstall "sdl2-image") and reinstall.

The files are where they are supposed to be:
$ ls -l /usr/lib/x86_64-linux-gnu/libSDL2_image-2.0.so
lrwxrwxrwx 1 root root 22 Nov 10 13:46 /usr/lib/x86_64-linux-gnu/libSDL2_image-2.0.so -> libSDL2_image-2.0.so.0
$ ls -l /usr/lib/x86_64-linux-gnu/libSDL2_image-2.0.so.0
lrwxrwxrwx 1 root root 26 Nov 10 13:46 /usr/lib/x86_64-linux-gnu/libSDL2_image-2.0.so.0 -> libSDL2_image-2.0.so.0.2.0
$ ls -l /usr/lib/x86_64-linux-gnu/libSDL2_image-2.0.so.0.2.0 
-rw-r--r-- 1 root root 134024 Nov 10 13:46 /usr/lib/x86_64-linux-gnu/libSDL2_image-2.0.so.0.2.0

Any idea whats wrong?
olli

**Comment by mfiano** [comment]
Cannot reproduce with the current code on Debian. Please re-open this if the issue still persists so that we can help you get it resolved.
