### ISSUE TITLE
LOAD-IMAGE does not document the fact that it frees the surface

### ISSUE THREAD

**Issue by RobertCochran** [lispgames/cl-sdl2-image#7]
I just fixed a problem in my game engine that's been on my radar for a couple weeks.

It boiled down to the fact that I was calling `sdl2:free-surface` unaware of the fact that `sdl2-image:load-image` was handling it in the finalizer. This lead to uncovering a race condition in my code where I would get dropped into the SBCL debugger.

I'm honestly not sure what to recommend to fix this. That the function exposed by this library does not correspond exactly to the C library is a little surprising. It was also mentioned on #lispgames that [cl-sdl2 has dropped automatic finalization](https://github.com/lispgames/cl-sdl2/commit/a963ea57c7d43761f28314f0642fcae18fb51174), so I'm inclined to say that sdl2-image should follow suit.

**Comment by mfiano** [comment]
This is on my todo list. cl-sdl2 recently removed finalizers. cl-sdl2-image should do the same. Expect a fix in a week or so, as it's low priority for me right now and I am quite busy. When I am finished, you will be required to clean up everything yourself, like the rest of cl-sdl2

**Comment by mfiano** [comment]
Looks like I had a few minutes free and removed the finalizers. This is fixed in 9c05c80. You can re-open this issue if you run into any problems.

**Comment by RobertCochran** [comment]
Looks good! Thanks for getting to this so quickly!
