### ISSUE TITLE
OSX install error on MacBook 2: missing sdl2-ffi:img-init-flags symbol

### ISSUE THREAD

**Issue by mirkov** [lispgames/cl-sdl2-image#9]
Hello,

I am trying to get Sketch going on my MacBookAir laptop & SBCL. First step is to get SDL libraries. I got SDL2 running. Now I need to get sdl2-image running.

The error I get when loading the system is:
```
CL-USER> (ql:quickload "sdl2-image")
To load "sdl2-image":
  Load 1 ASDF system:
    sdl2-image
; Loading "sdl2-image"
; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "IMG-INIT-FLAGS" not found in the SDL2-FFI package.
;   
;       Line: 7, Column: 73, File-Position: 259
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /Users/mirkov/.roswell/lisp/quicklisp/dists/quicklisp/software/cl-sdl2-image-20190202-git/src/general.lisp" {7005280793}>
; 
```

I got CL-SDL2 running following [the post](https://github.com/lispgames/cl-sdl2/issues/154#issuecomment-1280030566) which provides an updated `autowrap.lisp` and  `SDL2.aarch64-apple-darwin9.spec` files. I thought the same fix may work for sdl2-image.

I blindly applied the same fixes to SDL2-IMAGE as follows:

- Copy the same mods in `autowrap.lisp` changing the name of the `.h` file
- Regenerate the SPEC files
- Copy the SPEC file `SDL.aarch64-apple-darwin9.spec` into `SDL_image.aarch64-apple-darwin9.spec`
-  Restart SBCL and reload the ASDF file using `:force t`

Any thoughts on how to fix this problem? Is this even the right path? 

Thanks,

**Comment by ZachFontenot** [comment]
So that spec file is generated specifically for `SDL2` itself. We need to generate one for `SDL2_image` for `cl-autowrap` to have anything to work with. I'm following more or less the same example here.

**Comment by mirkov** [comment]
There is a discussion and a posted solution on this [Reddit Thread](https://www.reddit.com/r/Common_Lisp/comments/z5dnq8/sketch_sdl2_c2ffi_on_m1_mac/?utm_source=share&utm_medium=web2x&context=3).

I will close this issue, redirecting interested users to that discussion.

**Comment by mirkov** [comment]
There is a discussion and a posted solution on this [Reddit Thread](https://www.reddit.com/r/Common_Lisp/comments/z5dnq8/sketch_sdl2_c2ffi_on_m1_mac/?utm_source=share&utm_medium=web2x&context=3).

I will close this issue, redirecting interested users to that discussion.
